### ISSUE TITLE
more `mode` placement options

### ISSUE THREAD

**Issue by brechmos-stsci** [denphi/jupyterlab-floatview#1]
I was wondering if there would be a way to be able to have more control over where the new views are placed. Something along the lines of a grid system is what I am thinking (rather than to the left, to the right, above and below).  I assume this would probably dive more into jupyterlab (of which I don't have a lot of experience).

```
Floatview(title='Image View', mode='split-right')
```

Maybe something like this (kinda Matplotlib'ish for the subplot where (x,y,z) creates an (x,y) grid and places the FloatView in the z'th location:
```
Floatview(title='Image View', mode=(3,3,1))
```

BTW, this package looks great and I like how I can python-ically create views with ipywidgets.

**Comment by denphi** [comment]
Unfortunately, that restriction comes from a library used by Jupyterlab front-end (phosphorJS http://phosphorjs.github.io/). 

If you are using recent versions of ipywidgets, you can use GridBox to mimic Matplotlib's layout and display it on a Floatview container

```
sc = Floatview(title='Floatview Output', mode='tab-after')
sl1 = IntSlider(description='Some slider', layout=Layout(width='auto', grid_area='sl1'))
sl2 = IntSlider(description='Some slider', layout=Layout(width='auto', grid_area='sl2'))
with sc:
    display(
        GridBox(children=[sl1,sl2], layout=Layout
           `(`
                    grid_template_rows='auto auto',
                    grid_template_columns='50% 50%',
                    grid_template_areas='''
                          "sl2 ."
                           ". sl1"
                    '''
            )
```

**Comment by brechmos-stsci** [comment]
Understood. That is a neat idea, I'll look at that. Thanks!
