### ISSUE TITLE
does not work on JupyterLab 1.0

### ISSUE THREAD

**Issue by LukaPitamic** [denphi/jupyterlab-floatview#2]
error raised when importing: `from floatview import Floatview`
![image](https://user-images.githubusercontent.com/34914144/62007538-10d51700-b13e-11e9-822a-82872ea5dc51.png)

I installed it by:
`pip install floatview`
&
`jupyter labextension install jupyterlab-floatview@0.1.11`

I don't need plotly at this point, only floating widget.

**Comment by denphi** [comment]
I haven't had time to completely test Floatview under JupyterLab 1.X. Hopefully coming weeks, I would find some time to complete the upgrade. 

If you want to load only the output widget without glueviz-widgets dependencies,  you can import it directly:

```
from floatview.floatview import Floatview
a = Floatview()
with a:
    display("MY CONTENT")
```

**Comment by denphi** [comment]
I have published a new version of floatview with support to JupyterLab 1.X. Let me know if you face any problem.

**Comment by LukaPitamic** [comment]
AWESOME!!! It all work like a charm! Thank you @denphi
