### ISSUE TITLE
"Active Tab" not "Active" by JupyterLab

### ISSUE THREAD

**Issue by LukaPitamic** [denphi/jupyterlab-floatview#4]
I'm using `floatview` as a context manager, mostly instead of right clicking and choosing`Create New View for Ouput` from context menu. 

I love it so much for setting up UI.

However since it does not really behave as a real tab I'm having difficulties making it full-screem as well as using keys shortcuts to move between tabs.

![image](https://user-images.githubusercontent.com/34914144/70846303-f501b180-1e4f-11ea-8437-dd2660861470.png)

Also it would be super great if in the future it would be possible to use is with something like:
`mode='tab-split-above'` and `'tab-split-bellow'` / `'tab-split-left'`  / `'tab-split-right'`. This would totally makes possible to setup whole UI (however complex it might be).

And again, great work @denphi !

**Comment by denphi** [comment]
The restriction on the "mode" option comes from phosphor (framework used by Jupyterlab)
https://github.com/phosphorjs/phosphor/blob/master/packages/widgets/src/docklayout.ts#L365

I will take a look on the "Active tab" issue,

**Comment by denphi** [comment]
New release of 0.3.1 added Floatview output as a MainAreaWidget that should fix the "No Active" issue,

By default the output window is not active, but this behavior can be changed passing the active option as True

`
  sc = Floatview(title='Floatview Output', mode='tab-after', active=True)
`

**Comment by LukaPitamic** [comment]
WOW!!! Amazing, it works exactly as you described! Now also _Single-Document Mode_ works as expected.
