### ISSUE TITLE
JupyterLab 2.x compatibility ATM?

### ISSUE THREAD

**Issue by LukaPitamic** [denphi/jupyterlab-floatview#6]
Any news about `floatview` JupyterLab >= 2.1 compatibility?

**Comment by denphi** [comment]
I just released a version that should be compatible with JupyterLab 2.X

jupyterlab-floatview 0.3.0
floatview 0.3.0

**Comment by LukaPitamic** [comment]
if works perfectly!!! Thank you @denphi !
